TAXONOMY = {
    "top": [
        "T-Shirts",
        "Shirts",
        "Blouses",
        "Polos",
        "Tank Tops",
        "Hoodies",
        "Sweatshirts",
        "Sweaters",
        "Cardigans",
    ],
    "bottom": [
        "Jeans",
        "Trousers",
        "Chinos",
        "Shorts",
        "Skirts",
        "Leggings",
        "Joggers",
    ],
    "outerwear": [
        "Jackets",
        "Coats",
        "Blazers",
        "Bomber Jackets",
        "Parkas",
        "Raincoats",
        "Vests",
    ],
    "dress_jumpsuit": [
        "Casual Dresses",
        "Evening Dresses",
        "Maxi Dresses",
        "Mini Dresses",
        "Party Dresses",
        "Jumpsuits",
        "Playsuits",
    ],
    "set": [
        "Matching Sets",
        "Tracksuits",
        "Lounge Sets",
        "Suit Sets",
    ],
    "activewear": [
        "Sports Tops",
        "Sports Bras",
        "Gym Leggings",
        "Training Shorts",
        "Tracksuits",
        "Performance Jackets",
    ],
    "sleepwear": [
        "Pajama Sets",
        "Nightgowns",
        "Robes",
        "Lounge Pants",
        "Homewear Tops",
    ],
    "underwear_basics": [
        "Briefs / Boxers",
        "Bras",
        "Socks",
        "Undershirts",
        "Shapewear",
    ],
    "swimwear": [
        "Bikini Sets",
        "One-piece Swimsuits",
        "Swim Shorts",
        "Cover-Ups / Kaftans",
    ],
    "traditional": [
        "Abaya",
        "Kaftan",
        "Thobe / Kandura",
        "Kurta Sets",
    ],
}
